### ISSUE TITLE
Update Fastify Dependency to v3

### ISSUE THREAD

**Issue by henriqueleite42** [benMain/aws-serverless-fastify#26]
Hello!

Thanks for your package, it's very useful!

Since fastify released version 3 more than 1 year ago, I would like to know if it would be possible to update the package dependency to use version 3.

This is mainly due to problems running `serlerss package`, when it runs the command `npm ls -prod -json -depth=1` and finds incompatibility between the version used by the package `aws-serverless-fastify` (v2 .6.x) is the version used in the local project (v3.22.x).

From the [migration guide](https://www.fastify.io/docs/latest/Migration-Guide-V3/), I imagine that this change could cause a lot of problems for those who are using v2, but eventually it will have to happen, and the longer we postpone it, the worse it will be.

Thanks again, and I await your feedback.

**Comment by benMain** [comment]
@henriqueleite42 I'm sure you've long since moved on but that support exists now in version 2.x
