### ISSUE TITLE
Variadic listen method is deprecated error logged for every API call

### ISSUE THREAD

**Issue by adamduren** [benMain/aws-serverless-fastify#60]
(node:8) [FSTDEP011] FastifyDeprecation: Variadic listen method is deprecated. Please use ".listen(optionsObject)" instead. The variadic signature will be removed in `fastify@5`.
(Use `node --trace-warnings ...` to show where the warning was created)

**Comment by adamduren** [comment]
@benMain is this an easy change on your end? I have not contributed to this library before and only lightly use Fastify but I believe I could make the change if it's as straight forward as the warning suggests and there's no consideration regarding compatibility with other versions of Fastify this library might provide.

**Comment by benMain** [comment]
@adamduren I think we've got it. Sorry I sometimes lose track of my repos.

**Comment by adamduren** [comment]
@benMain I completely understand that. Very helpful library. Thank you!
